<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;

class Products extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            "name"=>"required",
            "brand"=>"required",
            "price"=>"required",
            "stock_quantity"=>"required|integer"
        ];
    }

    public function messages()
    {
        return [
            "name.required"=>"Por favor, informe o nome do Produto",
            "brand.required"=>"Por favor, informe a marca do Produto",
            "price.required"=>"Por favor, informe o preço do Produto",
            "stock_quantity.required"=>"Por favor, informe a quantidade em estoque do Produto",
            "stock_quantity.integer"=>"Somente números inteiros pode ser informado na quantidade em estoque"
        ];
        //return parent::messages(); // TODO: Change the autogenerated stub
    }

    protected function failedValidation(Validator $validator)
    {
        throw new HttpResponseException(response()->json(
            [
                "result"=>0,
                "errors" => $validator->messages()
            ], 400
        ));
        //parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }

}
